### ISSUE TITLE
Add a license to shell script?

### ISSUE THREAD

**Issue by marhop** [k3mpaxl/fanspeed#1]
Hi, your script works great on my ProBook 430 G2 with some minimal adaptions, thanks for that! Will you add a license statement to your shell script (the Perl file already contains one) so I can publish my modifications? I know, this is a bit nit-picky, but who am I to infringe your copyright ;-)

Thanks,
Martin

**Comment by k3mpaxl** [comment]
Hi Martin,

I added a license to the files. 

Best regards,
Gregor

**Comment by marhop** [comment]
Great, thank you, that was fast!
